"""updated avatar length

Revision ID: 3d11f862b1ce
Revises: 6d493f6ea6cb
Create Date: 2022-02-14 00:41:14.915357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d11f862b1ce'
down_revision = '6d493f6ea6cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('users', 'image_url')
    # ### end Alembic commands ###
