"""updated subscribers table

Revision ID: 6d493f6ea6cb
Revises: c12a68dbf03f
Create Date: 2022-02-12 22:09:39.109200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d493f6ea6cb'
down_revision = 'c12a68dbf03f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscribers', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscribers', 'name')
    # ### end Alembic commands ###
